theme: jekyll-theme-minimal
title: Juliana D. Adema
description: I'm a current Ph.D. student at University of Toronto, studying under the supervision of Dr. Michael Mack. My current research is focused on attentional guidance and visual search.
logo: /pics/avtr.jpg
